document.addEventListener('DOMContentLoaded', function() {
  const downloadBtn = document.getElementById('downloadBtn');
  const langBtns = document.querySelectorAll('.lang-btn');
  
  const translations = {
    en: {
      'title': 'Raynato Lienardy — CV (English)',
      'desc': 'CV of Raynato Lienardy, Full-Stack Web & Mobile Developer specializing in web, mobile, and AI/ML integrations.',
      'og-title': 'Raynato Lienardy — Full-Stack Web & Mobile Developer',
      'og-desc': 'Full-Stack Web & Mobile Developer building web, mobile, and AI-integrated applications. Experience with React, Flutter, Laravel, Python, and AI/ML tools.',
      'summary-title': 'Professional Summary',
      'summary-text': 'Full-Stack Web & Mobile Developer building web, mobile, and AI-integrated applications. Work with React, Flutter, Laravel, Python, and AI/ML tools in real projects. Experience working on software projects during internships, individually and in teams.',
      'skills-title': 'Technical Skills',
      'skill-frontend': '<strong>Frontend:</strong> HTML, CSS, JavaScript, React, Tailwind CSS',
      'skill-backend': '<strong>Backend:</strong> Python, PHP, Laravel, REST API Integration',
      'skill-mobile': '<strong>Mobile:</strong> Flutter, Dart, React Native, Java',
      'skill-db': '<strong>Database & Backend Services:</strong> MySQL, PostgreSQL, Supabase, Firebase',
      'skill-aiml': '<strong>AI/ML:</strong> TensorFlow, TensorFlow.js, PyTorch, MediaPipe, OpenCV',
      'skill-tools': '<strong>Tools:</strong> Git, GitHub, Docker, Linux, VS Code',
      'experience-title': 'Experience',
      'exp1-date': 'March 2023 – June 2023',
      'exp1-sub': 'MultiBlog Project (Team of 5)',
      'exp1-b1': 'Worked on backend for MultiBlog — a social-media-style web app — using Laravel.',
      'exp1-b2': 'Helped define the backend flow and kept the database structure aligned with the application code.',
      'exp1-b3': 'Implemented backend features together with 2 designers, another backend developer, and a frontend developer.',
      'exp2-title': 'Software Engineering Intern — Telkom AI Center of Excellence, PT Telkom Indonesia',
      'exp2-date': 'June 2026 – August 2026',
      'exp2-b1': 'Built three individual AI projects published as tools/showcase on the organization\'s official website.',
      'exp2-b2': 'Built T-Save prototype with a team of 3 — a medicine tracking app using barcode, AI/ML, and blockchain — and presented the technical work and use case at Mini Demo Day.',
      'exp2-b3': 'Joined the AIC Makassar partnership program and helped with technical demos and project presentations.',
      'projects-title': 'Featured Projects',
      'project-link-gesture': 'Live Demo',
      'gesture-b1': 'Web app for real-time gesture and sign-language recognition. Uses MediaPipe for tracking and LSTM for sequence classification.',
      'gesture-b2': 'Runs the trained model directly in the browser with TensorFlow.js, no server processing needed.',
      'project-link-arcane': 'Live Demo',
      'arcane-b1': 'Web app where users upload a PDF and get quiz questions generated by AI.',
      'arcane-b2': 'React + Vite frontend connected to a Python/FastAPI backend for document processing and quiz generation.',
      'project-link-face': 'Live Demo',
      'face-b1': 'Web app for facial feature analysis using computer vision and deep learning.',
      'face-b2': 'Uses InsightFace, ONNX Runtime, PyTorch, and OpenCV for face processing and feature extraction.',
      'education-title': 'Education',
      'education-unm-sub': 'S1 Pendidikan Teknik Informatika dan Komputer — GPA: 3.65 / 4.00',
      'lang-ach-title': 'Languages & Achievements',
      'lang-text': '<strong>Indonesian:</strong> Native | <strong>English:</strong> Intermediate / Professional Working Proficiency | <strong>Japanese:</strong> Beginner',
      'ach1': '<strong>3rd Winner</strong> — Web Design Competition, Electro Invention Race (2023)',
      'ach2': '<strong>3rd Winner</strong> — Web Design Competition, Electro Invention Race (2022)',
      'download-title': 'Download CV as PDF',
      'photo-fallback': 'Photo',
      'photo-alt': 'Profile photo of Raynato Lienardy',
      'pdf-file-protocol-msg': 'PDF cannot be generated from local file. Please use HTTP server: python -m http.server 8000, then open http://localhost:8000'
    },
    id: {
      'title': 'Raynato Lienardy — CV (Indonesia)',
      'desc': 'CV Raynato Lienardy, Full-Stack Web & Mobile Developer dengan pengalaman dalam pengembangan web, mobile, dan integrasi AI/ML.',
      'og-title': 'Raynato Lienardy — Full-Stack Web & Mobile Developer',
      'og-desc': 'Full-Stack Web & Mobile Developer yang membangun aplikasi web, mobile, dan fitur berbasis AI. Pengalaman dengan React, Flutter, Laravel, Python, dan tools AI/ML.',
      'summary-title': 'Ringkasan Profesional',
      'summary-text': 'Full-Stack Web & Mobile Developer yang membangun aplikasi web, mobile, dan fitur berbasis AI. Menggunakan React, Flutter, Laravel, Python, dan tools AI/ML di proyek nyata. Berpengalaman mengerjakan proyek software saat magang, baik individu maupun tim.',
      'skills-title': 'Keahlian Teknis',
      'skill-frontend': '<strong>Frontend:</strong> HTML, CSS, JavaScript, React, Tailwind CSS',
      'skill-backend': '<strong>Backend:</strong> Python, PHP, Laravel, Integrasi REST API',
      'skill-mobile': '<strong>Mobile:</strong> Flutter, Dart, React Native, Java',
      'skill-db': '<strong>Database & Backend Services:</strong> MySQL, PostgreSQL, Supabase, Firebase',
      'skill-aiml': '<strong>AI/ML:</strong> TensorFlow, TensorFlow.js, PyTorch, MediaPipe, OpenCV',
      'skill-tools': '<strong>Tools:</strong> Git, GitHub, Docker, Linux, VS Code',
      'experience-title': 'Pengalaman',
      'exp1-date': 'Maret 2023 – Juni 2023',
      'exp1-sub': 'Proyek MultiBlog (Tim 5 orang)',
      'exp1-b1': 'Mengerjakan backend MultiBlog — aplikasi web bertema media sosial — menggunakan Laravel.',
      'exp1-b2': 'Membantu menyusun alur aplikasi dari sisi backend dan menyesuaikan struktur database dengan kebutuhan aplikasi.',
      'exp1-b3': 'Mengerjakan fitur backend bersama 2 desainer, satu backend developer lain, dan satu frontend developer.',
      'exp2-title': 'Software Engineering Intern — Telkom AI Center of Excellence, PT Telkom Indonesia',
      'exp2-date': 'Juni 2026 – Agustus 2026',
      'exp2-b1': 'Membuat tiga proyek AI individu yang dipublikasikan sebagai tools/showcase di website resmi organisasi.',
      'exp2-b2': 'Membuat prototipe T-Save bersama tim ber-3 — aplikasi tracking obat dengan barcode, AI/ML, dan blockchain — dan mempresentasikan sisi teknis serta use case di Mini Demo Day.',
      'exp2-b3': 'Mengikuti program kemitraan AIC Makassar dan membantu demo teknis serta presentasi proyek.',
      'projects-title': 'Proyek Unggulan',
      'project-link-gesture': 'Demo Langsung',
      'gesture-b1': 'Aplikasi web untuk pengenalan gestur/bahasa isyarat real-time. Menggunakan MediaPipe untuk tracking dan LSTM untuk klasifikasi sekuens.',
      'gesture-b2': 'Model berjalan langsung di browser dengan TensorFlow.js tanpa perlu pemrosesan server.',
      'project-link-arcane': 'Demo Langsung',
      'arcane-b1': 'Aplikasi web untuk upload PDF dan membuat soal kuis otomatis dengan AI.',
      'arcane-b2': 'Frontend React + Vite terhubung ke backend Python/FastAPI untuk memproses dokumen dan generate kuis.',
      'project-link-face': 'Demo Langsung',
      'face-b1': 'Aplikasi web untuk analisis fitur wajah dengan computer vision dan deep learning.',
      'face-b2': 'Menggunakan InsightFace, ONNX Runtime, PyTorch, dan OpenCV untuk pemrosesan wajah dan ekstraksi fitur.',
      'education-title': 'Pendidikan',
      'education-unm-sub': 'S1 Pendidikan Teknik Informatika dan Komputer — IPK: 3.65 / 4.00',
      'lang-ach-title': 'Bahasa & Prestasi',
      'lang-text': '<strong>Bahasa Indonesia:</strong> Native | <strong>Bahasa Inggris:</strong> Intermediate / Professional Working Proficiency | <strong>Bahasa Jepang:</strong> Beginner',
      'ach1': '<strong>Juara 3</strong> — Web Design Competition, Electro Invention Race (2023)',
      'ach2': '<strong>Juara 3</strong> — Web Design Competition, Electro Invention Race (2022)',
      'download-title': 'Unduh CV sebagai PDF',
      'photo-fallback': 'Foto',
      'photo-alt': 'Foto profil Raynato Lienardy',
      'pdf-file-protocol-msg': 'PDF tidak bisa dibuat dari file lokal. Harap gunakan HTTP server: python -m http.server 8000, lalu buka http://localhost:8000'
    }
  };

  const switcherAria = {
    en: {
      en: 'Switch to English',
      id: 'Switch to Indonesian'
    },
    id: {
      en: 'Ganti ke Bahasa Inggris',
      id: 'Ganti ke Bahasa Indonesia'
    }
  };

  function setLanguage(lang) {
    if (!translations[lang]) return;
    
    document.documentElement.lang = lang;
    localStorage.setItem('cv-lang', lang);

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (translations[lang][key] !== undefined) {
        el.innerHTML = translations[lang][key];
      }
    });

    document.querySelectorAll('[data-i18n-title]').forEach(el => {
      const key = el.getAttribute('data-i18n-title');
      if (translations[lang][key] !== undefined) {
        el.setAttribute('title', translations[lang][key]);
      }
    });

    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc && translations[lang]['desc']) {
      metaDesc.setAttribute('content', translations[lang]['desc']);
    }

    const ogTitle = document.querySelector('meta[property="og:title"]');
    if (ogTitle && translations[lang]['og-title']) {
      ogTitle.setAttribute('content', translations[lang]['og-title']);
    }

    const ogDesc = document.querySelector('meta[property="og:description"]');
    if (ogDesc && translations[lang]['og-desc']) {
      ogDesc.setAttribute('content', translations[lang]['og-desc']);
    }

    document.title = translations[lang]['title'];

    langBtns.forEach(btn => {
      const btnLang = btn.getAttribute('data-lang');
      const isActive = btnLang === lang;
      btn.classList.toggle('active', isActive);
      btn.setAttribute('aria-pressed', isActive ? 'true' : 'false');
      if (switcherAria[lang] && switcherAria[lang][btnLang]) {
        btn.setAttribute('aria-label', switcherAria[lang][btnLang]);
      }
    });
  }

  langBtns.forEach(btn => {
    btn.addEventListener('click', function() {
      const selectedLang = this.getAttribute('data-lang');
      setLanguage(selectedLang);
    });
  });

  const savedLang = localStorage.getItem('cv-lang');
  setLanguage(savedLang === 'id' ? 'id' : 'en');

  downloadBtn.addEventListener('click', async function() {
    if (typeof html2pdf === 'undefined') {
      const msg = document.documentElement.lang === 'id' ? 'Library PDF belum dimuat. Periksa koneksi internet dan refresh halaman.' : 'PDF library not loaded. Check internet connection and refresh.';
      alert(msg);
      console.error('html2pdf is not defined — CDN failed to load');
      return;
    }
    const currentLang = document.documentElement.lang;
    const filename = currentLang === 'id' ? 'Raynato_Lienardy_CV_ID.pdf' : 'Raynato_Lienardy_CV.pdf';
    const originalContent = downloadBtn.innerHTML;
    const generatingText = currentLang === 'id' ? '<span>Membuat...</span>' : '<span>Generating...</span>';
    downloadBtn.innerHTML = generatingText;
    downloadBtn.disabled = true;
    const element = document.querySelector('.cv-container');
    try {
      if (document.fonts && document.fonts.ready) await document.fonts.ready;
      const imgs = element.querySelectorAll('img');
      await Promise.all(Array.from(imgs).map(img => {
        if (img.style.display === 'none') return Promise.resolve();
        if (img.complete && img.naturalWidth !== 0) return Promise.resolve();
        return new Promise(resolve => {
          img.addEventListener('load', resolve, { once: true });
          img.addEventListener('error', resolve, { once: true });
        });
      }));
      element.classList.add('pdf-export');
      await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));
      const opt = {
        margin: 0.28,
        filename: filename,
        image: { type: 'jpeg', quality: 0.92 },
        html2canvas: { scale: 1.5, useCORS: false, backgroundColor: '#ffffff', logging: false, scrollX: 0, scrollY: 0 },
        jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: [] }
      };
      await html2pdf().from(element).set(opt).save();
    } catch (err) {
      console.error('PDF generation error:', err);
      const fileProtocol = window.location.protocol === 'file:';
      const msg = fileProtocol
        ? (currentLang === 'id' ? 'PDF tidak bisa dibuat dari file lokal. Harap gunakan HTTP server: python -m http.server 8000, lalu buka http://localhost:8000' : 'PDF cannot be generated from local file. Please use HTTP server: python -m http.server 8000, then open http://localhost:8000')
        : (currentLang === 'id' ? 'Gagal membuat PDF. Silakan coba lagi.' : 'Failed to generate PDF. Please try again.');
      alert(msg);
      if (!fileProtocol) console.error('PDF error details:', err);
    } finally {
      element.classList.remove('pdf-export');
      downloadBtn.innerHTML = originalContent;
      downloadBtn.disabled = false;
    }
  });
});

